// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_the_beginner = "CgkI98SbiogaEAIQBg"; // <GPGSID>
        public const string achievement_triple = "CgkI98SbiogaEAIQDg"; // <GPGSID>
        public const string achievement_avid_swiper = "CgkI98SbiogaEAIQCw"; // <GPGSID>
        public const string achievement_bank_shot = "CgkI98SbiogaEAIQDA"; // <GPGSID>
        public const string achievement_one_small_step = "CgkI98SbiogaEAIQBQ"; // <GPGSID>
        public const string achievement_monochromatic = "CgkI98SbiogaEAIQDw"; // <GPGSID>
        public const string achievement_the_journeyman = "CgkI98SbiogaEAIQCQ"; // <GPGSID>
        public const string achievement_the_apprentice = "CgkI98SbiogaEAIQCA"; // <GPGSID>
        public const string achievement_the_novice = "CgkI98SbiogaEAIQBw"; // <GPGSID>
        public const string achievement_the_master = "CgkI98SbiogaEAIQCg"; // <GPGSID>
        public const string achievement_double = "CgkI98SbiogaEAIQDQ"; // <GPGSID>
        public const string leaderboard_score = "CgkI98SbiogaEAIQBA"; // <GPGSID>

}

